### ISSUE TITLE
from MySQL to MongoDB/CouchDB/RethinkDB

### ISSUE THREAD

**Issue by ghost** [blooprint/blooprint-api#4]
For ease of interaction with [blooprint.xyz](https://github.com/ddaaggeett/blooprint.xyz)'s dynamic web presence with ReactJS and Webpack, images used throughout the [Blooprint platform](http://www.blooprint.xyz) will be in file format (not binary as per MySQL) and referred to by a `string` object from JSON storage instead.

**Comment by ddaaggeett** [comment]
Blooprint is a desktop application and uses the hard drive per local machine.  A database will not be required.  Perhaps once the desktop application is running for the individual user, we can create a [hub] environment that hosts repositories of Blooprint projects similar to GitHub.
